-- MySQL Script generated by MySQL Workbench
-- Mon Jan 20 20:17:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema groundwatermeasurement
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema groundwatermeasurement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `groundwatermeasurement` DEFAULT CHARACTER SET utf8 ;
USE `groundwatermeasurement` ;

-- -----------------------------------------------------
-- Table `groundwatermeasurement`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groundwatermeasurement`.`roles` (
  `ID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `groundwatermeasurement`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groundwatermeasurement`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `roles_ID` INT UNIQUE NOT NULL,
  PRIMARY KEY (`roles_ID`),
  CONSTRAINT `fk_user_roles1`
    FOREIGN KEY (`roles_ID`)
    REFERENCES `groundwatermeasurement`.`roles` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `groundwatermeasurement`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groundwatermeasurement`.`clients` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `sub_topic` VARCHAR(45) NOT NULL,
  `pub_topic` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `location` VARCHAR(45) NOT NULL,
  `running` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `groundwatermeasurement`.`measurements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groundwatermeasurement`.`measurements` (
  `ID` INT UNIQUE NOT NULL AUTO_INCREMENT,
  `clients_ID` INT NOT NULL,
  `timestamp` DATETIME NULL,
  `water_height` INT UNSIGNED NULL,
  `pump_running` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_measurements_clients`
    FOREIGN KEY (`clients_ID`)
    REFERENCES `groundwatermeasurement`.`clients` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
